INSERT INTO shopping_list.ingredients (name) VALUES ('jajka');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt grecki');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt naturalny');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt smakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt skyr');
INSERT INTO shopping_list.ingredients (name) VALUES ('kefir');
INSERT INTO shopping_list.ingredients (name) VALUES ('natka pietruszki');
INSERT INTO shopping_list.ingredients (name) VALUES ('pietruszka');
INSERT INTO shopping_list.ingredients (name) VALUES ('pietruszka suszona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kluski śląskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('margaryna');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło');
INSERT INTO shopping_list.ingredients (name) VALUES ('maślanka');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło klarowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko 2%');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko 3,2%');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko 1,5%');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko kokosowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko migdałowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko owsiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko sojowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('śmietana');
INSERT INTO shopping_list.ingredients (name) VALUES ('camembert');
INSERT INTO shopping_list.ingredients (name) VALUES ('cheddar');
INSERT INTO shopping_list.ingredients (name) VALUES ('edam');
INSERT INTO shopping_list.ingredients (name) VALUES ('feta');
INSERT INTO shopping_list.ingredients (name) VALUES ('gorgonzola');
INSERT INTO shopping_list.ingredients (name) VALUES ('gouda');
INSERT INTO shopping_list.ingredients (name) VALUES ('halumi');
INSERT INTO shopping_list.ingredients (name) VALUES ('mascarpone');
INSERT INTO shopping_list.ingredients (name) VALUES ('mozarella');
INSERT INTO shopping_list.ingredients (name) VALUES ('parmezan');
INSERT INTO shopping_list.ingredients (name) VALUES ('ricotta');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser kozi');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser feta');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser pleśniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser Camembert');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser mozzarella');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser topiony');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser żółty');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser żółty tarty');
INSERT INTO shopping_list.ingredients (name) VALUES ('serek kanapkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('serek wiejski');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg chudy');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg półtłusty');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg tłusty');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka biała');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka gryczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka kokosowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka orkiszowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka owsiana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka pszenna');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka pszenna graham');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka razowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka ryżowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka ziemniaczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('ziemniaki');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka żytnia');
INSERT INTO shopping_list.ingredients (name) VALUES ('amarantus');
INSERT INTO shopping_list.ingredients (name) VALUES ('bulgur');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza gryczana niepalona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza gryczana prażona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jaglana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna pęczak');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna wiejska');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna perłowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('komosa ryżowa (quinoa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza kuskus');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza bulgur');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza manna');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza owsiana pęczak');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza owsiana łamana');
INSERT INTO shopping_list.ingredients (name) VALUES ('polenta');
INSERT INTO shopping_list.ingredients (name) VALUES ('polędwiczka wieprzowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż basmati');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż biały');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż brązowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż dziki');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż jaśminowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('soczewica');
INSERT INTO shopping_list.ingredients (name) VALUES ('granola');
INSERT INTO shopping_list.ingredients (name) VALUES ('musli');
INSERT INTO shopping_list.ingredients (name) VALUES ('mintaj');
INSERT INTO shopping_list.ingredients (name) VALUES ('musli z orzechami');
INSERT INTO shopping_list.ingredients (name) VALUES ('otręby owiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki drożdżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki gryczane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki jaglane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki orkiszowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki owsiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki quinoa');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki żytnie');
INSERT INTO shopping_list.ingredients (name) VALUES ('herbata czarna');
INSERT INTO shopping_list.ingredients (name) VALUES ('herbata ziołowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('hebata zielona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kakao (proszek)');
INSERT INTO shopping_list.ingredients (name) VALUES ('kawa');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła do drobiu');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła do schabu');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła prowansalskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła do sałatek');
INSERT INTO shopping_list.ingredients (name) VALUES ('wafle ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('napój energetyczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('napój gazowany');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok owocowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok z cytryny');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda gazowana');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda niegazowana');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda kokosowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda mineralna');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda źródlana');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier');
INSERT INTO shopping_list.ingredients (name) VALUES ('cynamon (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('grejpfrut');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukinia');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier brązowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier brzozowy (ksylitol)');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier trzcinowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier puder');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód lipowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód gryczany');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód wielokwiatowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód rzepakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód spadziowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('syrop klonowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('syrop z agawy');
INSERT INTO shopping_list.ingredients (name) VALUES ('awokado');
INSERT INTO shopping_list.ingredients (name) VALUES ('ciecierzyca');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola biała');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola czarna');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola konserwowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('groszek w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('kapary');
INSERT INTO shopping_list.ingredients (name) VALUES ('frankfurterka');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomarańcza');
INSERT INTO shopping_list.ingredients (name) VALUES ('koncentrat pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('przecier pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('kukurydza');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek kiszony');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek konserwowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek małosolny');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek gruntowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek szklarniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('rzodkiewka');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki zielone');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki zielone w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki zielone marynowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki czarne');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki czarne w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki czarne marynowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('poimdory suszone w oleju');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory krojone');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory suszone');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory suszone w zalewie');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory w całości');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory koktajlowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory daktylowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory rzymskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory paprykowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory zielone');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory malinowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory żółte');
INSERT INTO shopping_list.ingredients (name) VALUES ('soczewica konserwowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk w oleju');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk w sosie własnym');
INSERT INTO shopping_list.ingredients (name) VALUES ('łosoś filet');
INSERT INTO shopping_list.ingredients (name) VALUES ('łosoś wędzony');
INSERT INTO shopping_list.ingredients (name) VALUES ('aromat');
INSERT INTO shopping_list.ingredients (name) VALUES ('banan');
INSERT INTO shopping_list.ingredients (name) VALUES ('bakalie');
INSERT INTO shopping_list.ingredients (name) VALUES ('przyprawa włoska');
INSERT INTO shopping_list.ingredients (name) VALUES ('przyprawa do ziemniaków');
INSERT INTO shopping_list.ingredients (name) VALUES ('przyprawa do ryb');
INSERT INTO shopping_list.ingredients (name) VALUES ('bazylia (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('bazylia świeża');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier waniliowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('drożdże');
INSERT INTO shopping_list.ingredients (name) VALUES ('ekstrakt migdałowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ekstrakt waniliowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('gorzka czekolada');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko kondensowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('proszek do pieczenia');
INSERT INTO shopping_list.ingredients (name) VALUES ('skrobia kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('skrobia ziemniaczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('soda oczyszczona');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron farfalle (koradki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron fusili (świderki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron gnocchi (muszelki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron gryczany');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron jajeczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron penne (rurka skośna)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron penne pełnoziarnisty (rurka skośna)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron ryżowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron spaghetti');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron spaghetti pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron tagliatelle (wstążki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('chrzan');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka zielona');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka żułta');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka chili');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka słodka (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka ostra (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem truskawkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem wiśniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem porzeczkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem malinowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem jagodowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem brzoskwiniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem morelowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ketchup');
INSERT INTO shopping_list.ingredients (name) VALUES ('kostka bulionowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('bulion warzywny');
INSERT INTO shopping_list.ingredients (name) VALUES ('majonez');
INSERT INTO shopping_list.ingredients (name) VALUES ('burak');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło orzechowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('musztarda');
INSERT INTO shopping_list.ingredients (name) VALUES ('pasta curry');
INSERT INTO shopping_list.ingredients (name) VALUES ('curry (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('pesto');
INSERT INTO shopping_list.ingredients (name) VALUES ('salsa');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok cytrynowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok limonkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos BBQ');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos sojowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos Worcestshire');
INSERT INTO shopping_list.ingredients (name) VALUES ('sriracha');
INSERT INTO shopping_list.ingredients (name) VALUES ('tahini (pasta sezamowa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały');
INSERT INTO shopping_list.ingredients (name) VALUES ('laska wanili');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały płatki');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały słupki');
INSERT INTO shopping_list.ingredients (name) VALUES ('nasiona Chia');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy nerkowca');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy arachidowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy brazylijskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy laskowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy włoskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzeszki piniowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pestki dyni');
INSERT INTO shopping_list.ingredients (name) VALUES ('pistacje');
INSERT INTO shopping_list.ingredients (name) VALUES ('sezam (nasiona)');
INSERT INTO shopping_list.ingredients (name) VALUES ('siemie lnianie');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiórki kokosowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('ziarna słonecznika');
INSERT INTO shopping_list.ingredients (name) VALUES ('bób');
INSERT INTO shopping_list.ingredients (name) VALUES ('brokuły');
INSERT INTO shopping_list.ingredients (name) VALUES ('brukselka');
INSERT INTO shopping_list.ingredients (name) VALUES ('dynia');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasolka szparagowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('groszek');
INSERT INTO shopping_list.ingredients (name) VALUES ('jarmuż');
INSERT INTO shopping_list.ingredients (name) VALUES ('kalafior');
INSERT INTO shopping_list.ingredients (name) VALUES ('marchew');
INSERT INTO shopping_list.ingredients (name) VALUES ('rukola');
INSERT INTO shopping_list.ingredients (name) VALUES ('kolendra świeża');
INSERT INTO shopping_list.ingredients (name) VALUES ('kolendra (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('mieszanka warzyw');
INSERT INTO shopping_list.ingredients (name) VALUES ('mieszanka sałat');
INSERT INTO shopping_list.ingredients (name) VALUES ('warzywa mrożone wiosenne');
INSERT INTO shopping_list.ingredients (name) VALUES ('szpinak');
INSERT INTO shopping_list.ingredients (name) VALUES ('szpinak mrożony');
INSERT INTO shopping_list.ingredients (name) VALUES ('czarna porzeczka');
INSERT INTO shopping_list.ingredients (name) VALUES ('czarnuszka');
INSERT INTO shopping_list.ingredients (name) VALUES ('jagody');
INSERT INTO shopping_list.ingredients (name) VALUES ('jagody mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('jeżyny mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('maliny');
INSERT INTO shopping_list.ingredients (name) VALUES ('maliny mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('śliwki');
INSERT INTO shopping_list.ingredients (name) VALUES ('truskawki');
INSERT INTO shopping_list.ingredients (name) VALUES ('truskawki mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiśnie');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiśnie mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('koper');
INSERT INTO shopping_list.ingredients (name) VALUES ('sałata');
INSERT INTO shopping_list.ingredients (name) VALUES ('sałata lodowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('sałata masłowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet balsamiczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet jabłkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet ryżowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet spirytusowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet winny');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej kokosowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej lniany');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej rzepakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej sezamowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej słonecznikowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej z pestek winogron');
INSERT INTO shopping_list.ingredients (name) VALUES ('winogrona');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwa z oliwek');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb graham');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb pszenny');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb zwykły');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni razowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni jasny');
INSERT INTO shopping_list.ingredients (name) VALUES ('szczypiorek');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz czarny');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz biały');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz biały mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz czarny mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz kolorowy mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz kolorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('rozmaryn');
INSERT INTO shopping_list.ingredients (name) VALUES ('tymianek');
INSERT INTO shopping_list.ingredients (name) VALUES ('majeranek');
INSERT INTO shopping_list.ingredients (name) VALUES ('sól');
INSERT INTO shopping_list.ingredients (name) VALUES ('bułka grahamka');
INSERT INTO shopping_list.ingredients (name) VALUES ('bułka pszenna');
INSERT INTO shopping_list.ingredients (name) VALUES ('bułka maślana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kajzerka');
INSERT INTO shopping_list.ingredients (name) VALUES ('brzoskwinia');
INSERT INTO shopping_list.ingredients (name) VALUES ('len nasiona');
INSERT INTO shopping_list.ingredients (name) VALUES ('len mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula żółta');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula cukrowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula szalotka');
INSERT INTO shopping_list.ingredients (name) VALUES ('czosnek');
INSERT INTO shopping_list.ingredients (name) VALUES ('mięso mielone z indyka');
INSERT INTO shopping_list.ingredients (name) VALUES ('mięso mielone z kurczaka');
INSERT INTO shopping_list.ingredients (name) VALUES ('indyk filet');
INSERT INTO shopping_list.ingredients (name) VALUES ('kurczak filet');
INSERT INTO shopping_list.ingredients (name) VALUES ('borówki');
INSERT INTO shopping_list.ingredients (name) VALUES ('borówki mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('jabłko');
INSERT INTO shopping_list.ingredients (name) VALUES ('gruszka');
INSERT INTO shopping_list.ingredients (name) VALUES ('schab');
INSERT INTO shopping_list.ingredients (name) VALUES ('daktyle');
INSERT INTO shopping_list.ingredients (name) VALUES ('kiełki');
INSERT INTO shopping_list.ingredients (name) VALUES ('kiwi');
INSERT INTO shopping_list.ingredients (name) VALUES ('wanilia ekstrakt');
INSERT INTO shopping_list.ingredients (name) VALUES ('wanilia laska');
INSERT INTO shopping_list.ingredients (name) VALUES ('daktyle suszone');
INSERT INTO shopping_list.ingredients (name) VALUES ('oregano (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('szynka z indyka');
INSERT INTO shopping_list.ingredients (name) VALUES ('szynka z kurczaka');
INSERT INTO shopping_list.ingredients (name) VALUES ('kiełbasa żywiecka sucha');
INSERT INTO shopping_list.ingredients (name) VALUES ('budyń waniliowy (proszek)');

INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('poniedziałek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('wtorek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('środa');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('czwartek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('piątek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('sobota');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('niedziela');

INSERT INTO shopping_list.meal_names (meal_name) VALUES ('śniadanie');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('II śniadanie');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('obiad');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('podwieczorek');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('kolacja');

INSERT INTO shopping_list.users (id, created_on, email, first_name, last_name, password, role, updated_on) VALUES (1, '2020-12-03 10:31:32.113075', 'machniom93@gmail.com', 'Mateusz', 'Machnio', '$2a$10$hqTF64smXPXPX5mNEG2/o.9vv4tgk8Guce3HWO3BW0F194lSiTZ4a', 'USER', null);





INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (1);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (2);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (3);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (4);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (5);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (6);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (7);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (8);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (9);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (10);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (11);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (12);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (13);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (14);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (15);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (16);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (17);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (18);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (19);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (20);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (21);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (22);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (23);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (24);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (25);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (26);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (27);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (28);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (29);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (30);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (31);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (32);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (33);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (34);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (35);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (36);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (37);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (38);
INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (39);

INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (1, 60, 303, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (2, 5, 12, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (3, 60, 46, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (4, 50, 3, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (5, 5, 296, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (6, 60, 152, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (7, 50, 150, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (8, 5, 311, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (9, 120, 326, null, 2);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (10, 12, 245, null, 2);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (11, 150, 282, null, 2);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (12, 5, 327, null, 2);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (13, 220, 114, null, 2);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (14, 25, 329, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (15, 4, 333, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (16, 130, 334, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (17, 50, 205, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (18, 6, 290, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (19, 10, 302, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (20, 200, 160, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (21, 3, 183, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (22, 2, 212, null, 3);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (23, 65, 338, null, 4);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (24, 150, 5, null, 4);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (25, 72, 279, null, 4);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (26, 30, 310, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (27, 5, 12, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (28, 5, 287, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (29, 20, 351, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (30, 70, 301, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (31, 60, 288, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (32, 130, 163, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (33, 65, 209, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (34, 25, 329, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (35, 5, 275, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (36, 5, 290, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (37, 5, 302, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (38, 5, 129, null, 5);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (39, 60, 303, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (40, 60, 46, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (41, 6, 184, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (42, 5, 333, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (43, 10, 302, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (44, 9, 153, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (45, 130, 163, null, 6);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (46, 30, 303, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (47, 50, 1, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (48, 10, 3, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (49, 2, 212, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (50, 5, 43, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (51, 2, 311, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (52, 50, 338, null, 7);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (53, 100, 1, null, 8);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (54, 5, 297, null, 8);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (55, 220, 13, null, 8);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (56, 75, 3, null, 8);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (57, 150, 150, null, 8);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (58, 280, 60, null, 8);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (59, 150, 3, null, 9);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (60, 30, 89, null, 9);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (61, 60, 304, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (62, 5, 12, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (63, 70, 46, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (64, 4, 333, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (65, 25, 3, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (66, 100, 150, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (67, 3, 302, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (68, 60, 152, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (69, 5, 112, null, 10);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (70, 60, 309, null, 11);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (71, 5, 12, null, 11);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (72, 10, 287, null, 11);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (73, 60, 1, null, 11);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (74, 16, 352, null, 11);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (75, 65, 209, null, 11);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (76, 100, 178, null, 12);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (77, 100, 5, null, 12);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (78, 100, 143, null, 12);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (79, 4, 333, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (80, 120, 337, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (81, 7, 126, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (82, 10, 302, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (83, 130, 163, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (84, 3, 180, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (85, 30, 287, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (86, 10, 112, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (87, 60, 72, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (88, 6, 7, null, 13);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (89, 25, 3, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (90, 60, 345, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (91, 75, 282, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (92, 90, 279, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (93, 5, 12, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (94, 4, 249, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (95, 7, 90, null, 14);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (96, 60, 310, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (97, 7, 161, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (98, 50, 134, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (99, 3, 333, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (100, 60, 138, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (101, 5, 302, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (102, 60, 163, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (103, 3, 349, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (104, 3, 212, null, 15);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (105, 60, 307, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (106, 5, 12, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (107, 120, 164, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (108, 60, 46, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (109, 50, 134, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (110, 30, 350, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (111, 5, 112, null, 16);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (112, 150, 326, null, 17);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (113, 18, 245, null, 17);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (114, 75, 282, null, 17);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (115, 90, 10, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (116, 50, 329, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (117, 10, 302, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (118, 60, 342, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (119, 13, 193, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (120, 2, 212, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (121, 200, 271, null, 18);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (122, 25, 348, null, 19);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (123, 5, 102, null, 19);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (124, 3, 327, null, 19);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (125, 8, 249, null, 19);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (126, 5, 255, null, 19);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (127, 10, 114, null, 19);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (128, 110, 142, null, 20);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (129, 60, 303, null, 20);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (130, 10, 344, null, 20);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (131, 5, 228, null, 20);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (132, 130, 163, null, 20);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (133, 10, 287, null, 20);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (134, 10, 242, null, 21);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (135, 220, 16, null, 21);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (136, 40, 95, null, 21);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (137, 75, 282, null, 21);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (138, 30, 309, null, 22);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (139, 5, 12, null, 22);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (140, 5, 287, null, 22);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (141, 20, 350, null, 22);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (142, 50, 147, null, 22);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (143, 160, 340, null, 22);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (144, 5, 333, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (145, 120, 337, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (146, 6, 286, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (147, 6, 126, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (148, 5, 228, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (149, 8, 302, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (150, 10, 112, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (151, 50, 73, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (152, 80, 340, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (153, 100, 265, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (154, 5, 296, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (155, 5, 112, null, 23);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (156, 60, 310, null, 24);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (157, 20, 217, null, 24);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (158, 150, 45, null, 24);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (159, 25, 330, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (160, 100, 150, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (161, 5, 302, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (162, 10, 153, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (163, 50, 209, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (164, 150, 163, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (165, 2, 183, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (166, 60, 288, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (167, 30, 37, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (168, 2, 106, null, 25);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (169, 110, 337, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (170, 50, 201, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (171, 5, 296, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (172, 5, 302, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (173, 28, 162, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (174, 25, 266, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (175, 3, 104, null, 26);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (176, 20, 353, null, 27);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (177, 5, 118, null, 27);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (178, 60, 279, null, 27);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (179, 140, 16, null, 27);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (180, 60, 303, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (181, 5, 12, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (182, 10, 287, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (183, 15, 42, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (184, 20, 351, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (185, 25, 329, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (186, 5, 302, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (187, 180, 163, null, 28);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (188, 60, 310, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (189, 1, 112, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (190, 5, 12, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (191, 40, 134, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (192, 55, 1, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (193, 25, 3, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (194, 2, 212, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (195, 5, 311, null, 29);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (196, 100, 178, null, 30);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (197, 100, 5, null, 30);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (198, 12, 249, null, 30);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (199, 100, 226, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (200, 25, 329, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (201, 3, 112, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (202, 4, 333, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (203, 140, 336, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (204, 10, 302, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (205, 2, 183, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (206, 1, 349, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (207, 1, 318, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (208, 1, 319, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (209, 50, 68, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (210, 5, 296, null, 31);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (211, 5, 126, null, 32);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (212, 60, 46, null, 32);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (213, 100, 282, null, 32);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (214, 20, 108, null, 32);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (215, 60, 303, null, 33);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (216, 30, 163, null, 33);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (217, 2, 183, null, 33);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (218, 40, 39, null, 33);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (219, 120, 341, null, 33);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (220, 60, 339, null, 34);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (221, 60, 280, null, 34);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (222, 10, 242, null, 34);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (223, 5, 126, null, 34);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (224, 220, 15, null, 34);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (225, 30, 95, null, 34);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (226, 60, 308, null, 35);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (227, 5, 12, null, 35);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (228, 40, 209, null, 35);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (229, 10, 287, null, 35);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (230, 20, 351, null, 35);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (231, 150, 326, null, 36);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (232, 18, 245, null, 36);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (233, 75, 282, null, 36);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (234, 60, 303, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (235, 20, 329, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (236, 100, 150, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (237, 5, 302, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (238, 5, 153, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (239, 200, 163, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (240, 3, 183, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (241, 15, 288, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (242, 30, 37, null, 37);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (243, 18, 348, null, 38);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (244, 50, 3, null, 38);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (245, 30, 66, null, 38);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (246, 60, 345, null, 38);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (247, 120, 15, null, 38);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (248, 10, 244, null, 38);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (249, 15, 287, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (250, 28, 161, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (251, 50, 209, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (252, 45, 152, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (253, 20, 37, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (254, 3, 311, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (255, 2, 107, null, 39);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (256, 5, 302, null, 39);


INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (1, '2020-12-11 17:53:20.480916', 'pyszne dietetyczne śniadanie', 'Chleb graham z twarożkiem i rzodkiewką', 1, true, 'Twaróg wymieszać z jogurtem, olejem, i drobno pokrojoną rzodkiewką. Przyprawić solą i pieprzem. Ułożyć na kromkach posmarowanych masłem. Na wierzch ułożyć plastry ogórka i posypać pokrojonym szczypiorkiem.', 10, null, 1);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (2, '2020-12-11 19:29:00.907531', '', 'Koktajl brzoskwiniowo-truskawkowy', 1, true, 'Owoce umyć. Brzoskwinię pokroić na kawałki. Wszystkie składniki przełożyć do wysokiego naczynia i zmiksować na gładką masę.', 5, null, 2);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (3, '2020-12-11 19:31:32.027763', '', 'Spaghetti bolognese', 1, true, 'Cebulę posiekać i podsmażyć na oliwie z oliwek. Dodać mięso i przyprawić papryką słodką, solą i pieprzem. Smażyć około 5 minut. Następnie dodać pomidory, przeciśnięty przez praskę czosnek, bazylię i ocet balsamiczny. Dusić pod przykryciem przez około 15 minut. Ugotować makaron i połączyć z przygotowanym sosem.', 40, null, 3);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (4, '2020-12-11 19:34:14.472114', '', 'Owoce leśne z jogurtem naturalnym', 1, true, 'Owoce umyć. Wszystkie składniki połączyć.', 5, null, 4);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (5, '2020-12-11 19:47:15.844253', 'bardzo pożywne śniadanie', 'Kanapki z szynką, sałatka warzywna z czarnuszką, owoc', 1, true, '1. Chleb posmarować masłem. Obłożyć szynką i umytą sałatą. \n2. Sałatę lodową, pomidora i paprykę umyć. Sałatę porwać na kawałki. Pomidora, paprykę i cebulę pokroić. Wszystkie warzywa wymieszać z sosem przygotowanym z oliwy, octu balsamicznego, miodu i pieprzu. Na wierzch posypać czarnuszką. \n3. Podawać z umytymi winogronami', 20, null, 5);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (6, '2020-12-11 20:20:11.721791', '', 'Bruschetta z pomidorem i oliwkami', 1, true, 'Pomidora i bazylię umyć. Pomidora pokroić w małą kostkę i wymieszać z bazylią. Kromki chleba opiec na grillu, jeszcze ciepłe natrzeć oliwą z przeciśniętym przez praskę czosnkiem i lekko posolić. Na każdej grzance ułożyć porcję serka, pomidorów, pokrojonych oliwek i przyprawić pieprzem. Podawać, gdy pieczywo jest jeszcze ciepłe.', 15, null, 6);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (7, '2020-12-11 20:26:24.192871', '', 'Kanapka z pastą jajeczną i szczypiorkiem, owoc', 1, true, 'Jajko ugotować i pokroić w drobną kostkę. Dodać starty ser, jogurt naturalny i szczypiorek. Doprawić papryką słodką, solą i pieprzem. Wymieszać. Gotową pastę położyć na kromkę chleba. Podawać z owocem, np. borówkami.', 10, null, 7);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (8, '2020-12-11 20:33:03.762552', '', 'Jajka sadzone z ziemniakami, mizerią i maślanką', 1, true, '1. Ziemniaki obrać, umyć i ugotować do miękkości. \n2. Jajka rozbić i wrzucić na rozgrzany olej. Przyprawić solą i pieprzem. Smażyć na małym ogniu do momentu aż się zetną. \n3. Ogórki umyć, obrać i pokroić w plasterki. Dodać jogurt i przyprawić solą i pieprzem. \n4. Podawać z maślanką.', 20, null, 8);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (9, '2020-12-11 20:35:27.715919', 'bardzo szybki deser', 'Musli z orzechami', 1, true, 'Przełożyć składniki do miski i wymieszać.', 2, null, 9);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (10, '2020-12-11 20:43:41.737978', '', 'Kanapka z twarogiem, sałatka z rzodkiewką i ogórki', 1, true, '1. Rzodkiewki oczyścić i pokroić w ćwiartki. Ogórka umyć, obrać i pokroić w półplasterki. Warzywa przełożyć do miski. Jogurt wymieszać z sokiem z cytryny i czosnkiem przeciśniętym przez praskę. Dodać do warzyw i wymieszać. Skropić oliwą. \n2. Kromki posmarować masłem i położyć plastry twarogu.', 15, null, 10);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (11, '2020-12-11 20:48:11.797064', '', 'Kanapka z szynką, sałatą i papryką, jajko na miękko', 1, true, 'Jajko ugotować na miękko. Chleb posmarować masłem, obłożyć sałatą, kiełbasą i papryką pokrojoną w paski.', 10, null, 11);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (12, '2020-12-11 20:53:05.769855', '', 'Koktajl pomarańczowo-bananowy', 1, true, 'Składniki przełożyć do wysokiego naczynia i zmiksować blenderem.', 5, null, 12);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (13, '2020-12-11 21:06:24.917728', '!!! Mięso trzeba wcześniej przygotować !!!', 'Aromatyczny filet z kurczaka na sałacie z kaszą kuskus', 1, true, '1. Zrobić marynatę: wymieszać oliwę, miód, sok z cytryny, posiekany czosnek i przyprawy. Mięso umyć, osuszyć i natrzeć marynatą (przygotować kilka godzin wcześniej lub na noc). \n2. Zamarynowane mięso włożyć do piekarnika i piec około 20-25 min. \n3. Kaszę zalać wrzącą wodą nieco ponad jej poziom. Przykryć i odstawić na 2-3 min. Gotową kaszę wymieszać i posypać posiekaną natką. \n4. Sałatę umyć i porwać na kawałki. Ułożyć na talerzu. Dookoła sałaty ułożyć pokrojonego w ósemki pomidora. Na wierzchu położyć upieczonego kurczaka.', 30, null, 13);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (14, '2020-12-11 21:14:10.843594', 'przepyszny deser', 'Crumble owocowe z otrębami i jogurtem', 1, true, 'Owoce umyć i osuszyć. Kiwi obrać ze skórki. Owoce pokroić na kawałki i wymieszać. Ułożyć w małym żaroodpornym naczyniu. Otręby wymieszać z zimnym masłem i posiekanym orzechem zagniatając jak kruszonkę. Wyłożyć na owoce i zapiekać około 20 minut w temperaturze 170 stopni. Ciepły deser udekorować jogurtem.', 30, null, 14);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (15, '2020-12-11 21:23:49.813196', '', 'Chleb pełnoziarnisty z pastą z czerwonej fasoli', 1, true, 'Fasolę odsączyć, przepłukać i włożyć do wysokiego naczynia razem z czosnkiem, oliwą, suszonymi pomidorami i przyprawami. Do smaku dodać sól i pieprz. Zblendować na gładką masę. Gotową pastą posmarować pieczywo. Podawać z awokado i pomidorami.', 10, null, 15);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (16, '2020-12-12 10:58:29.827287', '', 'Kanapka z szynką, sałatka z pomidorkami i awokado', 1, true, 'Pomidorki i awokado umyć. Pomidorki przekroić na pół. Awokado obrać, pokroić w kostkę i skropić sokiem z cytryny. Twaróg pokroić w kostkę. Wszystko wymieszać i oprószyć świeżo zmielonym pieprzem. Na posmarowany chleb masłem położyć plaster wędliny. ', 10, null, 16);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (17, '2020-12-12 11:01:01.371326', '', 'Owoce z orzechami nerkowca', 1, true, 'Owoce umyć i pokroić w kostkę. Przełożyć do miski i dodać orzechy.', 5, null, 17);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (18, '2020-12-12 11:10:18.354816', '', 'Bitki wieprzowe z kluskami śląskimi, warzywa', 1, true, '1. Mięso umyć i rozbić tłuczkiem. Obtoczyć w skrobi i natrzeć solą oraz pieprzem. Oliwę rozgrzać na patelni, dodać mięso i obsmażyć z każdej strony. Następnie dołożyć pokrojoną cebulkę i podlać mięso delikatnie wodą. Mięso dusić pod przykryciem ok. 30 min.. \n2. Mieszankę warzyw ugotować w wodzie z dodatkiem soli lub dusić na patelni pod przykryciem, podlewając niewielką ilością wody. Doprawić solą, pieprzem i słodką papryką.\n3. Kluski śląskie ugotować w wodzie z dodatkiem soli.', 40, null, 18);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (19, '2020-12-12 11:16:18.404523', 'bardzo sycący deser', 'Kulki orzechowo-czekoladowe', 1, true, 'Daktyle posiekać na kawałki. Wszystkie składniki oprócz wiórków kokosowych przełożyć do wysokiego naczynia i zblendować. Masę nabierać łyżeczką i formować dłonią kulki. Kulki obtoczyć w wiórkach i schłodzić w lodówce.', 10, null, 19);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (20, '2020-12-12 11:22:29.427293', '', 'Frankfurterka, kanapka z warzywami', 1, true, 'Frankfurterkę zagrzać w wodzie. Na pieczywo położyć warzywa. Podawać z musztardą lub ketchupem.', 10, null, 20);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (21, '2020-12-12 11:25:23.197045', '', 'Owsianka z truskawkami i migdałami', 1, true, 'Płatki owsiane gotować na mleku do miękkości. Przełożyć płatki do miski i ułożyć pokrojone truskawki. Oprószyć migdałami.', 15, null, 21);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (22, '2020-12-12 11:28:56.347468', '', 'Kanapka z wędliną i warzywami, owoc', 1, true, '1. Pieczywo posmarowane masłem obłożyć sałatą, szynką i ogórkiem.\n2. Podawać z umytym i pokrojonym jabłkiem.', 10, null, 22);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (23, '2020-12-12 11:40:38.408425', '', 'Grillowany filet z kurczaka w miodowo-musztardowej marynacie', 1, true, '1. Fileta umyć i dokładnie osuszyć papierowym ręcznikiem. Czosnek przecisnąć przez praskę i rozetrzeć z solą. Kurczaka skropić sokiem z cytryny, natrzeć czosnkiem z solą, posypać pieprzem i odstawić na 30 min do lodówki. \n2. Ugotować kaszę.\n3. Marchew i jabłko umyć i obrać. Zetrzeć na tarce o dużych oczkach. Dodać sok z cytryny i olej lniany. Wymieszać.\n4. Oliwę wymieszać z musztardą i miodem, koperek drobno posiekać. Mięso posmarować marynatą miodowo-musztardową, posypać koperkiem i grillować w piekarniku lub na patelni grillowej około 5 minut z każdej strony (w zależności od grubości).', 40, null, 23);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (24, '2020-12-12 11:43:15.655609', '', 'Chleb z dżemem i serkiem ziarnistym', 1, true, 'Serek połączyć z dżemem. Podawać z pieczywem.', 5, null, 24);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (25, '2020-12-12 11:49:51.996393', '', 'Sałatka grecka', 1, true, 'Warzywa umyć. Sałatę porwać na kawałki. Pomidora, ogórka i paprykę pokroić w kostkę a cebulę w plasterki. Pokrojone warzywa przełożyć do miski, dodać oliwki oraz przyprawy: sól, pieprz, bazylię i zioła prowansalskie. Następnie sałatkę skropić oliwą z oliwek i wymieszać. Na wierzchu sałatki pokruszyć ser feta.', 15, null, 25);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (26, '2020-12-12 11:59:02.098070', 'szybkie danie, może na wynos? :)', 'Makaron z kurczakiem, rukolą i suszonymi pomidorami', 1, true, '1. Ugotować makaron.\n2. Kurczaka umyć, pokroić w kostkę i smażyć na rozgrzanej oliwie. Dodać zioła do drobiu, cienkie plasterki pomidorów suszonych i rukolę. Dusić chwilę.\n3. Dodać ugotowany makaron i wymieszać. \n4. Gotowe danie skropić olejem lnianym lub oliwą.', 20, null, 26);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (27, '2020-12-12 12:03:06.750144', '', 'Budyń waniliowy z musem malinowym', 1, true, '1. Budyń ugotować według instrukcji na opakowaniu.\n2. Maliny zmiksować blenderem.\n3. Gotowy budyń przelać do miseczki i polać musem.', 10, null, 27);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (28, '2020-12-12 12:11:18.987706', '', 'Kanapki z polędwicą i żółtym serem, sałatka z pomidora', 1, true, '1. Chleb posmarowany masłem obłożyć sałatą, serem żółtym i szynką.\n2. Pomidora pokroić w półplasterki i przełożyć do miski. Cebulę posiekać i wymieszać z pomidorem. Przyprawić do smaku solą i pieprzem. Polać oliwą z oliwek lub olejem lnianym.', 10, null, 28);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (29, '2020-12-12 12:17:27.299909', '', 'Pieczywo z pastą jajeczną i szczypiorkiem', 1, true, 'Jajko ugotować i pokroić w drobną kostkę lub potrzeć na tarce. Awokado potrzeć na tarce, skropić sokiem z cytryny, wymieszać z jajkiem i jogurtem naturalnym. Doprawić solą, pieprzem i papryką. Wymieszać. Gotową pastę położyć na posmarowane masłem kromki chleba. Na wierzch położyć posiekany szczypiorek.', 15, null, 29);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (30, '2020-12-12 12:19:25.310645', '', 'Jogurt z bananem i orzechami', 1, true, 'Do salaterki przełożyć jogurt, dodać banana pokrojonego w plasterki i pokruszone orzechy włoskie.', 5, null, 30);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (31, '2020-12-12 12:30:39.201509', '', 'Filet z indyka w ziołach z kaszą jęczmienną, buraki tarte', 1, true, '1. Zioła wymieszać w miseczce z 2 łyżeczkami oiwy z oliwek. Do mieszanki przełożyć mięso, nacierać i odstawić do lodówki na około 20 minut. \n2. Ugotować buraki.\n3. Kaszę ugotować w wodzie z dodatkiem soli. Olej lniany spożyć po posiłku lub polać nim kaszę i wymieszać.\n4. Mięso zawinąć w folię aluminiową i piec w piekarniku nagrzanym do 200 stopni przez około 25 minut.\n5. Ugotowane buraki zetrzeć na tarce o grubych oczkach. Cebulę drobno posiekać i połączyć z burakami. Doprawić solą, pieprzem i sokiem z cytryny. Wymieszać.', 40, null, 31);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (32, '2020-12-12 12:33:33.613376', '', 'Wafle ryżowe z serkiem truskawkowym', 1, true, 'Ser twarogowy zmiksować z miodem i truskawkami. Gotową masą posmarować wafle ryżowe.', 5, null, 32);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (33, '2020-12-12 12:38:10.375249', '', 'Grzanki z camembertem i pomidorem, owoc', 1, true, 'Pieczywo opiec w tosterze lub opiekaczu. Położyć plasterki sera, pomidora i oprószyć ziołami. Podawać z gruszką.', 10, null, 33);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (34, '2020-12-12 21:37:19.379568', '', 'Owsianka z owocami i mlekiem', 1, true, 'Płatki owsiane zagotować z mlekiem. Następnie zdjąć z kuchenki i odstawić na kilka minut żeby płatki wchłonęły mleko. Maliny i borówki połączyć z miodem i zmiksować blenderem na mus (zostawić trochę borówek do udekorowania z wierzchu). Zmiksowane owoce dodać do owsianki i wymieszać. Z wierzchu udekorować borówkami i posypać płatkami migdałów.', 20, null, 34);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (35, '2020-12-12 21:40:42.601054', '', 'Kanapka z sałatą, wędliną i papryką', 1, true, 'Chleb posmarować, obłożyć sałatą, wędliną i na to położyć pokrojoną paprykę.', 5, null, 35);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (36, '2020-12-12 21:43:03.102361', '', 'Sałatka owocowa z orzechami', 1, true, 'Owoce umyć, pokroić i przełożyć do miski. Dodać orzechy i wymieszać.', 10, null, 36);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (37, '2020-12-12 21:51:07.915770', '', 'Sałatka grecka z chlebem graham', 1, true, 'Sałatę lodową umyć, osuszyć i porwać na małe kawałki. Pomidor sparzyć, obrać ze skórki i razem z ogórkiem pokroić w kostkę. Cebulę posiekać. Wszystkie składniki wymieszać z oliwą i przyprawami. Ser pokroić na kawałki i położyć na wierzch sałatki. Posypać pokrojonymi oliwkami. Podawać z  chlebem. Można ozdobić świeżą bazylią.', 15, null, 37);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (38, '2020-12-12 21:56:33.747567', '', 'Jaglanka z chia', 1, true, 'Kaszę jaglaną przelać wrzątkiem, przełożyć do garnka, dodać drobno pokrojone daktyle i nasiona chia. Zalać mlekiem i gotować około 12-15 min., aż kasza wchłonie mleko. Ugotowaną kaszę przełożyć do miseczki, dodać jogurt, udekorować pokrojonym w plasterki kiwi.', 20, null, 38);
INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (39, '2020-12-12 22:02:22.038295', '', 'Lekka sałatka warzywna', 1, true, 'Sałatę umyć, osuszyć, porwać na kawałki. Pomidory i oczyszczoną paprykę pokroić w kosteczkę. Ser pokroić w kostkę, rzodkiewki w półplasterki. Wszystko wymieszać, dodać posiekany szczypiorek oraz zioła. Tuż przed podaniem doprawić pieprzem i polać oliwą.', 15, null, 39);


INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 1);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 2);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 3);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 4);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 5);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 6);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 7);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 8);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 9);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 10);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 11);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 12);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 13);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 14);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 15);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 16);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 17);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 18);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 19);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 20);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 21);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 22);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 23);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 24);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 25);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 26);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 27);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 28);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 29);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 30);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 31);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 32);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 33);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 34);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 35);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 36);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 37);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 38);
INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 39);