INSERT INTO shopping_list.ingredients (name) VALUES ('jajka');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt grecki');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt naturalny');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt smakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('kefir');
INSERT INTO shopping_list.ingredients (name) VALUES ('margaryna');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło klarowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko kokosowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko migdałowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko owsiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko sojowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('śmietana');
INSERT INTO shopping_list.ingredients (name) VALUES ('camembert');
INSERT INTO shopping_list.ingredients (name) VALUES ('cheddar');
INSERT INTO shopping_list.ingredients (name) VALUES ('edam');
INSERT INTO shopping_list.ingredients (name) VALUES ('feta');
INSERT INTO shopping_list.ingredients (name) VALUES ('gorgonzola');
INSERT INTO shopping_list.ingredients (name) VALUES ('gouda');
INSERT INTO shopping_list.ingredients (name) VALUES ('halumi');
INSERT INTO shopping_list.ingredients (name) VALUES ('mascarpone');
INSERT INTO shopping_list.ingredients (name) VALUES ('mozarella');
INSERT INTO shopping_list.ingredients (name) VALUES ('parmezan');
INSERT INTO shopping_list.ingredients (name) VALUES ('ricotta');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser kozi');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser pleśniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser topiony');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser żółty');
INSERT INTO shopping_list.ingredients (name) VALUES ('serek kanapkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('serek wiejski');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka biała');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka gryczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka kokosowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka orkiszowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka owsiana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka pszenna');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka razowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka ryżowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka ziemniaczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka żytnia');
INSERT INTO shopping_list.ingredients (name) VALUES ('amarantus');
INSERT INTO shopping_list.ingredients (name) VALUES ('bulgur');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza gryczana niepalona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza gryczana prażona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jaglana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna pęczak');
INSERT INTO shopping_list.ingredients (name) VALUES ('komosa ryżowa (quinoa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza kuskus');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza manna');
INSERT INTO shopping_list.ingredients (name) VALUES ('polenta');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż basmati');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż biały');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż brązowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż dziki');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż jaśminowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('soczewica');
INSERT INTO shopping_list.ingredients (name) VALUES ('granola');
INSERT INTO shopping_list.ingredients (name) VALUES ('musli');
INSERT INTO shopping_list.ingredients (name) VALUES ('otręby owiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki drożdżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki gryczane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki jaglane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki orkiszowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki owsiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki quinoa');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki żytnie');
INSERT INTO shopping_list.ingredients (name) VALUES ('herbata czarna');
INSERT INTO shopping_list.ingredients (name) VALUES ('herbata ziołowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('hebata zielona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kakao');
INSERT INTO shopping_list.ingredients (name) VALUES ('kawa');
INSERT INTO shopping_list.ingredients (name) VALUES ('napój energetyczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('napój gazowany');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok owocowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda gazowana');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda niegazowana');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda kokosowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier brązowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier brzozowy (ksylitol)');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier trzcinowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód');
INSERT INTO shopping_list.ingredients (name) VALUES ('syrop klonowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('syrop z agawy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ciecierzyca');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola biała');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola czarna');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('groszek w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('kapary');
INSERT INTO shopping_list.ingredients (name) VALUES ('koncentrat pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('kukurydza');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórki kiszone');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórki konserwowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki');
INSERT INTO shopping_list.ingredients (name) VALUES ('poimdory suszone w oleju');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory krojone');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory w całości');
INSERT INTO shopping_list.ingredients (name) VALUES ('przecier pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('soczewica konserwowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk');
INSERT INTO shopping_list.ingredients (name) VALUES ('łosoś');
INSERT INTO shopping_list.ingredients (name) VALUES ('aromat');
INSERT INTO shopping_list.ingredients (name) VALUES ('bakalie');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier waniliowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('drożdże');
INSERT INTO shopping_list.ingredients (name) VALUES ('ekstrakt migdałowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ekstrakt waniliowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('gorzka czekolada');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko kondensowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('proszek do pieczenia');
INSERT INTO shopping_list.ingredients (name) VALUES ('skrobia kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('soda oczyszczona');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron farfalle (koradki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron fusili (świderki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron gnocchi (muszelki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron gryczany');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron jajeczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron penne (rurka skośna)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron ryżowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron spaghetti');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron tagliatelle (wstążki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('chrzan');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem');
INSERT INTO shopping_list.ingredients (name) VALUES ('ketchup');
INSERT INTO shopping_list.ingredients (name) VALUES ('kostka bulionowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('majonez');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło orzechowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('musztarda');
INSERT INTO shopping_list.ingredients (name) VALUES ('pasta curry');
INSERT INTO shopping_list.ingredients (name) VALUES ('pesto');
INSERT INTO shopping_list.ingredients (name) VALUES ('salsa');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok cytrynowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok limonkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos BBQ');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos sojowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos Worcestshire');
INSERT INTO shopping_list.ingredients (name) VALUES ('sriracha');
INSERT INTO shopping_list.ingredients (name) VALUES ('tahini (pasta sezamowa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały');
INSERT INTO shopping_list.ingredients (name) VALUES ('nasiona Chia');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy nerkowca');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy arachidowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy brazylijskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy laskowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy włoskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzeszki piniowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pestki dyni');
INSERT INTO shopping_list.ingredients (name) VALUES ('pistacje');
INSERT INTO shopping_list.ingredients (name) VALUES ('sezam');
INSERT INTO shopping_list.ingredients (name) VALUES ('siemie lnianie');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiórki kokosowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('ziarna słonecznika');
INSERT INTO shopping_list.ingredients (name) VALUES ('bób');
INSERT INTO shopping_list.ingredients (name) VALUES ('brokuły');
INSERT INTO shopping_list.ingredients (name) VALUES ('brukselka');
INSERT INTO shopping_list.ingredients (name) VALUES ('dynia');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasolka szparagowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('groszek');
INSERT INTO shopping_list.ingredients (name) VALUES ('jarmuż');
INSERT INTO shopping_list.ingredients (name) VALUES ('kalafior');
INSERT INTO shopping_list.ingredients (name) VALUES ('marchewka');
INSERT INTO shopping_list.ingredients (name) VALUES ('mieszanka warzyw');
INSERT INTO shopping_list.ingredients (name) VALUES ('szpinak');
INSERT INTO shopping_list.ingredients (name) VALUES ('czarna porzeczka');
INSERT INTO shopping_list.ingredients (name) VALUES ('jagody');
INSERT INTO shopping_list.ingredients (name) VALUES ('jeżyny');
INSERT INTO shopping_list.ingredients (name) VALUES ('maliny');
INSERT INTO shopping_list.ingredients (name) VALUES ('śliwki');
INSERT INTO shopping_list.ingredients (name) VALUES ('truskawki');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiśnie');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet balsamiczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet jabłkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet ryżowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet spirytusowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet winny');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej kokosowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej lniany');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej rzepakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej sezamowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej słonecznikowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej z pestek winogron');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwa z oliwek');

INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('poniedziałek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('wtorek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('środa');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('czwartek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('piątek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('sobota');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('niedziela');

INSERT INTO shopping_list.meal_names (meal_name) VALUES ('śniadanie');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('II śniadanie');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('obiad');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('podwieczorek');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('kolacja');