INSERT INTO shopping_list.ingredients (name) VALUES ('jajka');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt grecki');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt naturalny');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt smakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('jogurt skyr');
INSERT INTO shopping_list.ingredients (name) VALUES ('kefir');
INSERT INTO shopping_list.ingredients (name) VALUES ('natka pietruszki');
INSERT INTO shopping_list.ingredients (name) VALUES ('pietruszka');
INSERT INTO shopping_list.ingredients (name) VALUES ('pietruszka suszona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kluski śląskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('margaryna');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło');
INSERT INTO shopping_list.ingredients (name) VALUES ('maślanka');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło klarowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko 2%');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko 3,2%');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko 1,5%');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko kokosowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko migdałowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko owsiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko sojowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('śmietana');
INSERT INTO shopping_list.ingredients (name) VALUES ('camembert');
INSERT INTO shopping_list.ingredients (name) VALUES ('cheddar');
INSERT INTO shopping_list.ingredients (name) VALUES ('edam');
INSERT INTO shopping_list.ingredients (name) VALUES ('feta');
INSERT INTO shopping_list.ingredients (name) VALUES ('gorgonzola');
INSERT INTO shopping_list.ingredients (name) VALUES ('gouda');
INSERT INTO shopping_list.ingredients (name) VALUES ('halumi');
INSERT INTO shopping_list.ingredients (name) VALUES ('mascarpone');
INSERT INTO shopping_list.ingredients (name) VALUES ('mozarella');
INSERT INTO shopping_list.ingredients (name) VALUES ('parmezan');
INSERT INTO shopping_list.ingredients (name) VALUES ('ricotta');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser kozi');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser feta');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser pleśniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser Camembert');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser mozzarella');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser topiony');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser żółty');
INSERT INTO shopping_list.ingredients (name) VALUES ('ser żółty tarty');
INSERT INTO shopping_list.ingredients (name) VALUES ('serek kanapkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('serek wiejski');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg chudy');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg półtłusty');
INSERT INTO shopping_list.ingredients (name) VALUES ('twaróg tłusty');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka biała');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka gryczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka kokosowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka orkiszowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka owsiana');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka pszenna');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka pszenna graham');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka razowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka ryżowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka ziemniaczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('ziemniaki');
INSERT INTO shopping_list.ingredients (name) VALUES ('mąka żytnia');
INSERT INTO shopping_list.ingredients (name) VALUES ('amarantus');
INSERT INTO shopping_list.ingredients (name) VALUES ('bulgur');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza gryczana niepalona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza gryczana prażona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jaglana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna pęczak');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna wiejska');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza jęczmienna perłowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('komosa ryżowa (quinoa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza kuskus');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza bulgur');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza manna');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza owsiana pęczak');
INSERT INTO shopping_list.ingredients (name) VALUES ('kasza owsiana łamana');
INSERT INTO shopping_list.ingredients (name) VALUES ('polenta');
INSERT INTO shopping_list.ingredients (name) VALUES ('polędwiczka wieprzowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż basmati');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż biały');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż brązowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż dziki');
INSERT INTO shopping_list.ingredients (name) VALUES ('ryż jaśminowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('soczewica');
INSERT INTO shopping_list.ingredients (name) VALUES ('granola');
INSERT INTO shopping_list.ingredients (name) VALUES ('musli');
INSERT INTO shopping_list.ingredients (name) VALUES ('mintaj');
INSERT INTO shopping_list.ingredients (name) VALUES ('musli z orzechami');
INSERT INTO shopping_list.ingredients (name) VALUES ('otręby owiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki drożdżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki gryczane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki jaglane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki orkiszowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki owsiane');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki quinoa');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('płatki żytnie');
INSERT INTO shopping_list.ingredients (name) VALUES ('herbata czarna');
INSERT INTO shopping_list.ingredients (name) VALUES ('herbata ziołowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('hebata zielona');
INSERT INTO shopping_list.ingredients (name) VALUES ('kakao (proszek)');
INSERT INTO shopping_list.ingredients (name) VALUES ('kawa');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła do drobiu');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła do schabu');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła prowansalskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('zioła do sałatek');
INSERT INTO shopping_list.ingredients (name) VALUES ('wafle ryżowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('napój energetyczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('napój gazowany');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok owocowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok z cytryny');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda gazowana');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda niegazowana');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda kokosowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda mineralna');
INSERT INTO shopping_list.ingredients (name) VALUES ('woda źródlana');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier');
INSERT INTO shopping_list.ingredients (name) VALUES ('cynamon (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('grejpfrut');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukinia');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier brązowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier brzozowy (ksylitol)');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier trzcinowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier puder');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód lipowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód gryczany');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód wielokwiatowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód rzepakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('miód spadziowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('syrop klonowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('syrop z agawy');
INSERT INTO shopping_list.ingredients (name) VALUES ('awokado');
INSERT INTO shopping_list.ingredients (name) VALUES ('ciecierzyca');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola biała');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola czarna');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasola konserwowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('groszek w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('kapary');
INSERT INTO shopping_list.ingredients (name) VALUES ('frankfurterka');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomarańcza');
INSERT INTO shopping_list.ingredients (name) VALUES ('koncentrat pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('przecier pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('kukurydza');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek kiszony');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek konserwowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek małosolny');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek gruntowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ogórek szklarniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('rzodkiewka');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki zielone');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki zielone w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki zielone marynowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki czarne');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki czarne w puszce');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwki czarne marynowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('poimdory suszone w oleju');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory krojone');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory suszone');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory suszone w zalewie');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory w całości');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory koktajlowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory daktylowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory rzymskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory paprykowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory paprykowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pomidory malinowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('przecier pomidorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('soczewica konserwowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk w oleju');
INSERT INTO shopping_list.ingredients (name) VALUES ('tuńczyk w sosie własnym');
INSERT INTO shopping_list.ingredients (name) VALUES ('łosoś filet');
INSERT INTO shopping_list.ingredients (name) VALUES ('łosoś wędzony');
INSERT INTO shopping_list.ingredients (name) VALUES ('aromat');
INSERT INTO shopping_list.ingredients (name) VALUES ('banan');
INSERT INTO shopping_list.ingredients (name) VALUES ('bakalie');
INSERT INTO shopping_list.ingredients (name) VALUES ('przyprawa włoska');
INSERT INTO shopping_list.ingredients (name) VALUES ('przyprawa do ziemniaków');
INSERT INTO shopping_list.ingredients (name) VALUES ('przyprawa do ryb');
INSERT INTO shopping_list.ingredients (name) VALUES ('bazylia (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('bazylia świeża');
INSERT INTO shopping_list.ingredients (name) VALUES ('cukier waniliowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('drożdże');
INSERT INTO shopping_list.ingredients (name) VALUES ('ekstrakt migdałowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ekstrakt waniliowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('gorzka czekolada');
INSERT INTO shopping_list.ingredients (name) VALUES ('mleko kondensowane');
INSERT INTO shopping_list.ingredients (name) VALUES ('proszek do pieczenia');
INSERT INTO shopping_list.ingredients (name) VALUES ('skrobia kukurydziana');
INSERT INTO shopping_list.ingredients (name) VALUES ('skrobia ziemniaczana');
INSERT INTO shopping_list.ingredients (name) VALUES ('soda oczyszczona');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron farfalle (koradki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron fusili (świderki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron gnocchi (muszelki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron gryczany');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron jajeczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron penne (rurka skośna)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron penne pełnoziarnisty (rurka skośna)');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron ryżowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron spaghetti');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron spaghetti pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('makaron tagliatelle (wstążki)');
INSERT INTO shopping_list.ingredients (name) VALUES ('chrzan');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka zielona');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka żułta');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka chili');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka słodka (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('papryka ostra (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem truskawkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem wiśniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem porzeczkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem malinowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem jagodowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem brzoskwiniowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('dżem morelowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ketchup');
INSERT INTO shopping_list.ingredients (name) VALUES ('kostka bulionowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('bulion warzywny');
INSERT INTO shopping_list.ingredients (name) VALUES ('majonez');
INSERT INTO shopping_list.ingredients (name) VALUES ('burak');
INSERT INTO shopping_list.ingredients (name) VALUES ('masło orzechowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('musztarda');
INSERT INTO shopping_list.ingredients (name) VALUES ('pasta curry');
INSERT INTO shopping_list.ingredients (name) VALUES ('curry (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('pesto');
INSERT INTO shopping_list.ingredients (name) VALUES ('salsa');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok cytrynowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sok limonkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos BBQ');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos sojowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('sos Worcestshire');
INSERT INTO shopping_list.ingredients (name) VALUES ('sriracha');
INSERT INTO shopping_list.ingredients (name) VALUES ('tahini (pasta sezamowa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały');
INSERT INTO shopping_list.ingredients (name) VALUES ('laska wanili');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały płatki');
INSERT INTO shopping_list.ingredients (name) VALUES ('migdały słupki');
INSERT INTO shopping_list.ingredients (name) VALUES ('nasiona Chia');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy nerkowca');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy arachidowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy brazylijskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy laskowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzechy włoskie');
INSERT INTO shopping_list.ingredients (name) VALUES ('orzeszki piniowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('pestki dyni');
INSERT INTO shopping_list.ingredients (name) VALUES ('pistacje');
INSERT INTO shopping_list.ingredients (name) VALUES ('sezam (nasiona)');
INSERT INTO shopping_list.ingredients (name) VALUES ('siemie lnianie');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiórki kokosowe');
INSERT INTO shopping_list.ingredients (name) VALUES ('ziarna słonecznika');
INSERT INTO shopping_list.ingredients (name) VALUES ('bób');
INSERT INTO shopping_list.ingredients (name) VALUES ('brokuły');
INSERT INTO shopping_list.ingredients (name) VALUES ('brukselka');
INSERT INTO shopping_list.ingredients (name) VALUES ('dynia');
INSERT INTO shopping_list.ingredients (name) VALUES ('fasolka szparagowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('groszek');
INSERT INTO shopping_list.ingredients (name) VALUES ('jarmuż');
INSERT INTO shopping_list.ingredients (name) VALUES ('kalafior');
INSERT INTO shopping_list.ingredients (name) VALUES ('marchew');
INSERT INTO shopping_list.ingredients (name) VALUES ('rukola');
INSERT INTO shopping_list.ingredients (name) VALUES ('kolendra świeża');
INSERT INTO shopping_list.ingredients (name) VALUES ('kolendra (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('mieszanka warzyw');
INSERT INTO shopping_list.ingredients (name) VALUES ('mieszanka sałat');
INSERT INTO shopping_list.ingredients (name) VALUES ('warzywa mrożone wiosenne');
INSERT INTO shopping_list.ingredients (name) VALUES ('szpinak');
INSERT INTO shopping_list.ingredients (name) VALUES ('szpinak mrożony');
INSERT INTO shopping_list.ingredients (name) VALUES ('czarna porzeczka');
INSERT INTO shopping_list.ingredients (name) VALUES ('czarnuszka');
INSERT INTO shopping_list.ingredients (name) VALUES ('jagody');
INSERT INTO shopping_list.ingredients (name) VALUES ('jagody mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('jeżyny mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('maliny');
INSERT INTO shopping_list.ingredients (name) VALUES ('maliny mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('śliwki');
INSERT INTO shopping_list.ingredients (name) VALUES ('truskawki');
INSERT INTO shopping_list.ingredients (name) VALUES ('truskawki mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiśnie');
INSERT INTO shopping_list.ingredients (name) VALUES ('wiśnie mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('koper');
INSERT INTO shopping_list.ingredients (name) VALUES ('sałata');
INSERT INTO shopping_list.ingredients (name) VALUES ('sałata lodowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('sałata masłowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet balsamiczny');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet jabłkowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet ryżowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet spirytusowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('ocet winny');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej kokosowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej lniany');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej rzepakowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej sezamowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej słonecznikowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('olej z pestek winogron');
INSERT INTO shopping_list.ingredients (name) VALUES ('winogrona');
INSERT INTO shopping_list.ingredients (name) VALUES ('oliwa z oliwek');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb graham');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb pszenny');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb zwykły');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni razowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni pełnoziarnisty');
INSERT INTO shopping_list.ingredients (name) VALUES ('chleb żytni jasny');
INSERT INTO shopping_list.ingredients (name) VALUES ('szczypiorek');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz czarny');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz biały');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz biały mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz czarny mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz kolorowy mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('pieprz kolorowy');
INSERT INTO shopping_list.ingredients (name) VALUES ('rozmaryn');
INSERT INTO shopping_list.ingredients (name) VALUES ('tymianek');
INSERT INTO shopping_list.ingredients (name) VALUES ('majeranek');
INSERT INTO shopping_list.ingredients (name) VALUES ('sól');
INSERT INTO shopping_list.ingredients (name) VALUES ('bułka grahamka');
INSERT INTO shopping_list.ingredients (name) VALUES ('bułka pszenna');
INSERT INTO shopping_list.ingredients (name) VALUES ('bułka maślana');
INSERT INTO shopping_list.ingredients (name) VALUES ('kajzerka');
INSERT INTO shopping_list.ingredients (name) VALUES ('brzoskwinia');
INSERT INTO shopping_list.ingredients (name) VALUES ('len nasiona');
INSERT INTO shopping_list.ingredients (name) VALUES ('len mielony');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula żółta');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula czerwona');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula cukrowa');
INSERT INTO shopping_list.ingredients (name) VALUES ('cebula szalotka');
INSERT INTO shopping_list.ingredients (name) VALUES ('czosnek');
INSERT INTO shopping_list.ingredients (name) VALUES ('mięso mielone z indyka');
INSERT INTO shopping_list.ingredients (name) VALUES ('mięso mielone z kurczaka');
INSERT INTO shopping_list.ingredients (name) VALUES ('indyk filet');
INSERT INTO shopping_list.ingredients (name) VALUES ('kurczak filet');
INSERT INTO shopping_list.ingredients (name) VALUES ('borówki');
INSERT INTO shopping_list.ingredients (name) VALUES ('borówki mrożone');
INSERT INTO shopping_list.ingredients (name) VALUES ('jabłko');
INSERT INTO shopping_list.ingredients (name) VALUES ('gruszka');
INSERT INTO shopping_list.ingredients (name) VALUES ('schab');
INSERT INTO shopping_list.ingredients (name) VALUES ('daktyle');
INSERT INTO shopping_list.ingredients (name) VALUES ('kiełki');
INSERT INTO shopping_list.ingredients (name) VALUES ('kiwi');
INSERT INTO shopping_list.ingredients (name) VALUES ('wanilia ekstrakt');
INSERT INTO shopping_list.ingredients (name) VALUES ('wanilia laska');
INSERT INTO shopping_list.ingredients (name) VALUES ('daktyle suszone');
INSERT INTO shopping_list.ingredients (name) VALUES ('oregano (przyprawa)');
INSERT INTO shopping_list.ingredients (name) VALUES ('szynka z indyka');
INSERT INTO shopping_list.ingredients (name) VALUES ('szynka z kurczaka');
INSERT INTO shopping_list.ingredients (name) VALUES ('kiełbasa żywiecka sucha');
INSERT INTO shopping_list.ingredients (name) VALUES ('budyń waniliowy (proszek)');

INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('poniedziałek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('wtorek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('środa');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('czwartek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('piątek');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('sobota');
INSERT INTO shopping_list.day_of_the_week (day_name) VALUES ('niedziela');

INSERT INTO shopping_list.meal_names (meal_name) VALUES ('śniadanie');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('II śniadanie');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('obiad');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('podwieczorek');
INSERT INTO shopping_list.meal_names (meal_name) VALUES ('kolacja');

INSERT INTO shopping_list.users (id, created_on, email, first_name, last_name, password, role, updated_on) VALUES (1, '2020-12-03 10:31:32.113075', 'machniom93@gmail.com', 'Mateusz', 'Machnio', '$2a$10$hqTF64smXPXPX5mNEG2/o.9vv4tgk8Guce3HWO3BW0F194lSiTZ4a', 'USER', null);





INSERT INTO shopping_list.set_of_ingredients_with_quantities (id) VALUES (1);

INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (1, 60, 303, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (2, 5, 12, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (3, 60, 46, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (4, 50, 3, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (5, 5, 296, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (6, 60, 152, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (7, 50, 150, null, 1);
INSERT INTO shopping_list.ingredients_with_quantities (id, quantity, ingredient_id, shopping_list_id, set_of_ingr_with_quant_id) VALUES (8, 5, 311, null, 1);

INSERT INTO shopping_list.recipes (id, created_on, description, name, number_of_servings, original, preparation, preparation_time, updated_on, set_of_ingr_with_quant_id) VALUES (1, '2020-12-11 17:53:20.480916', 'pyszne dietetyczne śniadanie', 'Chleb graham z twarożkiem i rzodkiewką', 1, true, 'Twaróg wymieszać z jogurtem, olejem, i drobno pokrojoną rzodkiewką. Przyprawić solą i pieprzem. Ułożyć na kromkach posmarowanych masłem. Na wierzch ułożyć plastry ogórka i posypać pokrojonym szczypiorkiem.', 10, null, 1);

INSERT INTO shopping_list.user_recipes (user_id, recipe_id) VALUES (1, 1);



